//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: paygw/proto/card/msg.proto

package card

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	//
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	//
	ExpMonth string `protobuf:"bytes,3,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	//
	ExpYear string `protobuf:"bytes,4,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	//
	Names []string `protobuf:"bytes,5,rep,name=names,proto3" json:"names,omitempty"`
	//
	Cvc string `protobuf:"bytes,6,opt,name=cvc,proto3" json:"cvc,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paygw_proto_card_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_paygw_proto_card_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_paygw_proto_card_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetExpMonth() string {
	if x != nil {
		return x.ExpMonth
	}
	return ""
}

func (x *Card) GetExpYear() string {
	if x != nil {
		return x.ExpYear
	}
	return ""
}

func (x *Card) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Card) GetCvc() string {
	if x != nil {
		return x.Cvc
	}
	return ""
}

//
type Authorization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	//
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	//
	Ns int64 `protobuf:"varint,3,opt,name=ns,proto3" json:"ns,omitempty"`
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paygw_proto_card_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_paygw_proto_card_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_paygw_proto_card_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Authorization) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Authorization) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Authorization) GetNs() int64 {
	if x != nil {
		return x.Ns
	}
	return 0
}

var File_paygw_proto_card_msg_proto protoreflect.FileDescriptor

var file_paygw_proto_card_msg_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x61, 0x79, 0x67, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61,
	0x72, 0x64, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x70, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x78, 0x70, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x78, 0x70, 0x59, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x76, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x76, 0x63, 0x22,
	0x47, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x6e, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x61, 0x79, 0x67,
	0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_paygw_proto_card_msg_proto_rawDescOnce sync.Once
	file_paygw_proto_card_msg_proto_rawDescData = file_paygw_proto_card_msg_proto_rawDesc
)

func file_paygw_proto_card_msg_proto_rawDescGZIP() []byte {
	file_paygw_proto_card_msg_proto_rawDescOnce.Do(func() {
		file_paygw_proto_card_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_paygw_proto_card_msg_proto_rawDescData)
	})
	return file_paygw_proto_card_msg_proto_rawDescData
}

var file_paygw_proto_card_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paygw_proto_card_msg_proto_goTypes = []interface{}{
	(*Card)(nil),          // 0: proto.card.Card
	(*Authorization)(nil), // 1: proto.card.Authorization
}
var file_paygw_proto_card_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paygw_proto_card_msg_proto_init() }
func file_paygw_proto_card_msg_proto_init() {
	if File_paygw_proto_card_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paygw_proto_card_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paygw_proto_card_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authorization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paygw_proto_card_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paygw_proto_card_msg_proto_goTypes,
		DependencyIndexes: file_paygw_proto_card_msg_proto_depIdxs,
		MessageInfos:      file_paygw_proto_card_msg_proto_msgTypes,
	}.Build()
	File_paygw_proto_card_msg_proto = out.File
	file_paygw_proto_card_msg_proto_rawDesc = nil
	file_paygw_proto_card_msg_proto_goTypes = nil
	file_paygw_proto_card_msg_proto_depIdxs = nil
}
